import type {Metadata} from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "town-manager",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
